### ISSUE TITLE
[BUG] NO suggestions when the query contains punctuations

### ISSUE THREAD

**Issue by timerring** [timerring/bilive#111]
## Describe the bug
When the query contains the punctuations, the bili api won't return any tags.

## Expected behavior
Fix the issue.

## Screenshots
```
Error: ResponseData { code: 21005, data: None, message: "Tag不能为空，总数量不能超过12个， 并且单个不能超过20个字", ttl: Some(1) }
```

## Environment Information
 - Operating System: [e.g. Ubuntu 20.04.5 LTS]
 - Python Version: [e.g. Python 3.9.15]
 - Driver & CUDA Version: [e.g. Driver 470.103.01 & CUDA 11.4]
 - Error Messages and Logs: [If applicable, provide any error messages or relevant log outputs]

**Comment by azio7** [comment]
正则处理后仍有可能返回空tags,建议判断返回tags为空时添加默认tags,比如主播昵称，直播切片
