### ISSUE TITLE
[BUG] 疑似默认配置项导致启动报错

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#118]
## Describe the bug
最新版本下
./setting.toml - space - check_interval 默认是0,启动失败,改成300就好了

**Comment by timerring** [comment]
好的感谢，这个配置应该是`blrec`中配置硬盘空间检测间隔的数值，我自己用的生产版本配置`check_interval`也是 0，意味着不检测，因为我写的规则里上传后直接删除原视频了，所以即使在超过 5 个房间同时录制视频时，占用的总空间也能控制在 50G 之内，因此我把默认的`recycle_records`回收空间给关了，所以`check_interval`这个参数可能意义不大，当然如果预留空间不足的话可以打开用于回收空间。

> 因为我写的规则里上传后直接删除原视频了

当然，如果不想删除的话，将`src/upload/upload.py`中`os.remove(upload_path)`改为需要的后处理操作即可。

**Comment by lululutx** [comment]
默认配置项还没改哦.这样新clone下的代码不更改配置是起不来webui的

space - check_interval 默认不能为 0
output - duration_limit 默认不能为 1200

**Comment by timerring** [comment]
好的，我调整一下，有推荐的参数设置吗？

**Comment by lululutx** [comment]
space - check_interval = 300
output - filesize_limit = 0

我目前是这样的，不一定是最好的配置，这样项目启动后就可以去webui里自己设置了

**Comment by timerring** [comment]
好的，稍后我 push 一版。
