### ISSUE TITLE
[BUG] 弹幕压制失败

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#130]
因为是nas上的虚拟机，所以无GPU

`GPU_EXIST=False
MODEL_TYPE = "append"`

scanLog
`2024-12-12 19:53:07 There is no file recorded. Check again in 120 seconds.
2024-12-12 19:55:07 There is no file recorded. Check again in 120 seconds.
Processing /home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.mp4...
The video resolution is 1280x720

DanmakuFactory 1.70 CLI Release by hkm (hkm@tikm.org)
https://github.com/hihkm/DanmakuFactory

Input file(s):
Number|Template     |TimeShift|FileName
     1|xml          |   0.000s|/home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.xml

Output file:
Format|FileName
   ass|/home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.ass

Loading files...
Loading file "/home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.xml"

File Loading Complete.. Danmaku Pool: 19983

Sorting...

Writting file "/home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.ass"...

Done!
The emojis of /home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.ass are removed.
The /home/lulu/Projects/bilive/Videos/14709735/14709735_20241212-18-56-50.ass has been processed.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 58, in <module>
    process_folder_append(room_folder)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 48, in process_folder_append
    render_video_only(file)
  File "/home/lulu/Projects/bilive/src/burn/only_render.py", line 42, in render_video_only
    render_video(original_video_path, format_video_path, subtitle_font_size, subtitle_margin_v)
  File "/home/lulu/Projects/bilive/src/burn/render_video.py", line 41, in render_video
    subprocess.run(command_without_gpu, stdout=log, stderr=subprocess.STDOUT)
NameError: name 'log' is not defined. Did you mean: 'blog'?
no gpu danmaku`

**Comment by timerring** [comment]
我的问题，写代码的时候漏了
```
with open(src.allconfig.BURN_LOG_PATH, 'a') as blog:
     subprocess.run(command_without_gpu, stdout=log, stderr=subprocess.STDOUT)
```
把 stdout=log 改成 stdout=blog 就行，我稍后推送一版。

**Comment by timerring** [comment]
已经推送，再试一下吧。

**Comment by timerring** [comment]
如果可以的话 pull 最新版本吧，我重构了配置文件。
