### ISSUE TITLE
[BUG] scan过程中找不到srt文件

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#140]
scanLog

`2024-12-14 17:54:37 There is no file recorded. Check again in 120 seconds.
2024-12-14 17:56:37 There is no file recorded. Check again in 120 seconds.
Processing /home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.mp4...
The video resolution is 1920x1080

DanmakuFactory 1.70 CLI Release by hkm (hkm@tikm.org)
https://github.com/hihkm/DanmakuFactory

Input file(s):
Number|Template     |TimeShift|FileName
     1|xml          |   0.000s|/home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.xml

Output file:
Format|FileName
   ass|/home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.ass

Loading files...
Loading file "/home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.xml"

File Loading Complete.. Danmaku Pool: 13801

Sorting...

Writting file "/home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.ass"...

Done!
The emojis of /home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.ass are removed.
The /home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.ass has been processed.
no gpu danmaku
complete danamku burning and wait for uploading!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 61, in <module>
    process_folder_append(room_folder)
  File "/home/lulu/Projects/bilive/src/burn/scan.py", line 49, in process_folder_append
    render_video_only(file)
  File "/home/lulu/Projects/bilive/src/burn/only_render.py", line 51, in render_video_only
    os.remove(remove_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lulu/Projects/bilive/Videos/14709735/14709735_20241214-16-57-50.srt'`

**Comment by timerring** [comment]
得，忘了没有 whisper 的机器没有字幕文件了，稍等我添加个存在判断。

**Comment by timerring** [comment]
现在应该正常了。原来为了方便测试取消忘添加回来了。
现在直接 pull 最新的代码就行。
