### ISSUE TITLE
[Help] 目前是否暴露了DanmakuFactory的参数？

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#142]
录制的主播观众很多,所以sc和弹幕也很多,渲染出来的观感就很诡异(图1)

我看项目内DanmakuFactory被打成了包 (src/utils/DanmakuFactory),请问我能自己修改吗?要修改哪个地方?请指教

需求
1、弹幕只在上面1/3或者1/4区域内渲染 (还是这个需求要在弹幕文件里修改)
2、sc的停留时间更短,添加一些透明度(我看DanmakuFactory有人实现了,但是我找不到咱们项目的接口)

图1
![image](https://github.com/user-attachments/assets/9ae25c5c-8be0-4aa0-90f3-6af9681f484d)

**Comment by timerring** [comment]
1. 因为 DanmakuFactory 底层是用 `C` 实现的，为了在 `python` 中方便集成，我采用了它编译后的版本。可以参考 [DanmakuFactory 的文档](https://github.com/hihkm/DanmakuFactory/blob/master/docs/DanmakuFactory%20CLI%20%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E.md) 查找对应的参数项，里面有显示弹幕范围等等参数。
2. 我根据不同的分辨率 fine-tune 了一些对应的参数，可以在 `src/burn/generate_danmakus.py` 中根据你所录制的视频分辨率添加或者修改对应的参数。

**Comment by lululutx** [comment]
ok我去瞧瞧☺
