### ISSUE TITLE
[BUG] 疑似未生成ass文件

### ISSUE THREAD

**Issue by lululutx** [timerring/bilive#146]
项目是新克隆下来的，修改的地方有这些
1、settings.toml
room_id
[danmaku]
danmu_uname = false
record_gift_send = false
record_free_gifts = false
record_guard_buy = false
record_super_chat = true
save_raw_danmaku = true

2、config.py
GPU_EXIST=False

MODEL_TYPE = "append"
Inference_Model = "small"

3、only_render.py
render_video(original_video_path, format_video_path, 15, 40) //上个issues说这个获取不到，我先写死了

4、extract_video_info.py
这里已经上传成功了，应该没影响

scanLog
`
2024-12-21 16:30:54 There is no file recorded. Check again in 120 seconds.
Processing /home/lulu/Projects/bilive/Videos/14709735/14709735_20241221-15-30-32.mp4...
Error: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x57be9298f540] moov atom not found
/home/lulu/Projects/bilive/Videos/14709735/14709735_20241221-15-30-32.mp4: Invalid data found when processing input

TypeError: expected str, bytes or os.PathLike object, not NoneType - Check the return value of process_danmakus
no gpu no danmaku
complete danamku burning and wait for uploading!
2024-12-21 16:32:55 There is no file recorded. Check again in 120 seconds.
`

**Comment by timerring** [comment]
确定是最新版本吗，我几个小时前 push 了一版，如果是的话，能不能在附件里提供一下 21 号完整的 scan 日志文件和对应的上传 upload 日志，我仔细分析一下。如果有敏感信息记得提前处理。

**Comment by lululutx** [comment]
确实 我又pull了一下就好了😭抱歉！
